### ISSUE TITLE
MS Edge fails to fetch created sessions.

### ISSUE THREAD

**Issue by venustulips** [hazelcast-guides/spring-session-hazelcast#4] opened 2021-01-08 08:02 UTC
I just cloned and run with IDE on port 8080.
Run only one instance, but session seems not being saved.

![image](https://user-images.githubusercontent.com/8254188/103989579-4c429480-51be-11eb-83e7-483d663961c0.png)

Using MS Edge Version 87 in case of any relevance.

**Comment by enozcan** [comment] 2021-01-08 08:09
Hi @venustulips,
Does it happen only with MS Edge? Have you tried with any other browser with the same SpringBoot app running?

**Comment by venustulips** [comment] 2021-01-08 08:10
Thanks for the prompt comment.

I just installed Firefox and it seems working on it. Seems only happening with MS Edge.
Is this something fixable from the server side?

**Comment by enozcan** [comment] 2021-01-08 08:12
I need to find the cause first before answering if it can be fixed on the server. I'm changing the issue header and will take a look at this asap and keep you informed. Thanks for reporting.

**Comment by venustulips** [comment] 2021-01-08 08:36
Thanks @enozcan, One more thing I noticed is that if I test with incognito mode, then it works with MS Edge too. I cleared all data from MS Edge and it is working now. Although I found nothing strange in DevTool, it seems either cookie or some other values were messed up.

**Comment by enozcan** [comment] 2021-01-11 07:15
@venustulips I've tried to reproduce with Edge 87.0.664.75 but it seems all OK. It's probably caused by - as you also pointed out, the existing cookies. Hence closing the issue. Please reopen/ask if you have any question.

**Closed by enozcan** 2021-01-11 07:15 UTC
